name: garza_et_al_2026
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.*
  - pip=25.1.1
  - numpy=2.1.*
  - pandas=2.3.*
  - pytables>=3.10
  - h5py>=3.12
  - numba=0.61.2
  - scipy=1.15.*
  - scikit-learn=1.7.*
  - matplotlib=3.10.*
  - seaborn=0.13.*
  - sympy=1.14.*
  - python-dotenv=1.1.0
  - scikit-optimize=0.10.2
  - pip:
    - navis==1.10.*
    - dash>=2.16.0,<3.0.0
    - dash-bootstrap-components>=1.5.0,<2.0.0
    - plotly>=5.18.0,<6.0.0